# Generated by Django 5.1 on 2024-09-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('ready_for_delivery', 'Готов для доставки'), ('in_transit', 'В пути'), ('completed', 'Завершен')], default='in_progress', max_length=100),
        ),
    ]
